"""initial schema

Revision ID: 1a047a077d5f
Revises:
Create Date: 2026-06-05 13:18:35.291394

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1a047a077d5f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instrument",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("manufacturer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("instrument", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_instrument_external_id"), ["external_id"], unique=False
        )

    op.create_table(
        "study",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("creator", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("references", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("persistence", sa.Boolean(), nullable=False),
        sa.Column("consecutively_manufactured", sa.Boolean(), nullable=False),
        sa.Column("nist_measurement", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_study_source_extid"),
    )
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_study_consecutively_manufactured"),
            ["consecutively_manufactured"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_study_external_id"), ["external_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_study_nist_measurement"), ["nist_measurement"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_study_persistence"), ["persistence"], unique=False)
        batch_op.create_index(batch_op.f("ix_study_source"), ["source"], unique=False)

    op.create_table(
        "firearm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("caliber", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("n_lands", sa.Integer(), nullable=True),
        sa.Column("twist", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("breech_face_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("firing_pin_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["study.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("firearm", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_firearm_brand"), ["brand"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_firearm_breech_face_class"), ["breech_face_class"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_firearm_caliber"), ["caliber"], unique=False)
        batch_op.create_index(batch_op.f("ix_firearm_external_id"), ["external_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_firearm_firing_pin_class"), ["firing_pin_class"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_firearm_n_lands"), ["n_lands"], unique=False)
        batch_op.create_index(batch_op.f("ix_firearm_study_id"), ["study_id"], unique=False)

    op.create_table(
        "bullet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firearm_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("surface_material", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["firearm_id"],
            ["firearm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bullet_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bullet_firearm_id"), ["firearm_id"], unique=False)

    op.create_table(
        "cartridgecase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firearm_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["firearm_id"],
            ["firearm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cartridgecase", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cartridgecase_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cartridgecase_firearm_id"), ["firearm_id"], unique=False
        )

    op.create_table(
        "land",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bullet_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bullet_id"],
            ["bullet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("land", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_land_bullet_id"), ["bullet_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_land_external_id"), ["external_id"], unique=False)

    op.create_table(
        "mark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cartridge_case_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mark_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cartridge_case_id"],
            ["cartridgecase.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mark", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mark_cartridge_case_id"), ["cartridge_case_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mark_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mark_mark_type"), ["mark_type"], unique=False)

    op.create_table(
        "scan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("land_id", sa.Integer(), nullable=True),
        sa.Column("mark_id", sa.Integer(), nullable=True),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("modality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("magnification", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lateral_resolution_x", sa.Float(), nullable=True),
        sa.Column("lateral_resolution_y", sa.Float(), nullable=True),
        sa.Column("light_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("x3p_meta_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.ForeignKeyConstraint(
            ["land_id"],
            ["land.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mark_id"],
            ["mark.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_instrument_id"), ["instrument_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_land_id"), ["land_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_scan_lateral_resolution_x"), ["lateral_resolution_x"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scan_mark_id"), ["mark_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_modality"), ["modality"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_source"))
        batch_op.drop_index(batch_op.f("ix_scan_modality"))
        batch_op.drop_index(batch_op.f("ix_scan_mark_id"))
        batch_op.drop_index(batch_op.f("ix_scan_lateral_resolution_x"))
        batch_op.drop_index(batch_op.f("ix_scan_land_id"))
        batch_op.drop_index(batch_op.f("ix_scan_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_scan_content_hash"))

    op.drop_table("scan")
    with op.batch_alter_table("mark", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mark_mark_type"))
        batch_op.drop_index(batch_op.f("ix_mark_external_id"))
        batch_op.drop_index(batch_op.f("ix_mark_cartridge_case_id"))

    op.drop_table("mark")
    with op.batch_alter_table("land", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_land_external_id"))
        batch_op.drop_index(batch_op.f("ix_land_bullet_id"))

    op.drop_table("land")
    with op.batch_alter_table("cartridgecase", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cartridgecase_firearm_id"))
        batch_op.drop_index(batch_op.f("ix_cartridgecase_external_id"))

    op.drop_table("cartridgecase")
    with op.batch_alter_table("bullet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bullet_firearm_id"))
        batch_op.drop_index(batch_op.f("ix_bullet_external_id"))

    op.drop_table("bullet")
    with op.batch_alter_table("firearm", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firearm_study_id"))
        batch_op.drop_index(batch_op.f("ix_firearm_n_lands"))
        batch_op.drop_index(batch_op.f("ix_firearm_firing_pin_class"))
        batch_op.drop_index(batch_op.f("ix_firearm_external_id"))
        batch_op.drop_index(batch_op.f("ix_firearm_caliber"))
        batch_op.drop_index(batch_op.f("ix_firearm_breech_face_class"))
        batch_op.drop_index(batch_op.f("ix_firearm_brand"))

    op.drop_table("firearm")
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_source"))
        batch_op.drop_index(batch_op.f("ix_study_persistence"))
        batch_op.drop_index(batch_op.f("ix_study_nist_measurement"))
        batch_op.drop_index(batch_op.f("ix_study_external_id"))
        batch_op.drop_index(batch_op.f("ix_study_consecutively_manufactured"))

    op.drop_table("study")
    with op.batch_alter_table("instrument", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instrument_external_id"))

    op.drop_table("instrument")
    # ### end Alembic commands ###
