"""add scan trace + pair diagnostic

Revision ID: 5ed39b57d680
Revises: 1a047a077d5f
Create Date: 2026-06-06 12:03:05.212818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ed39b57d680'
down_revision: Union[str, Sequence[str], None] = '1a047a077d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairdiagnostic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('bullet_a_id', sa.Integer(), nullable=False),
    sa.Column('bullet_b_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('diag_mean', sa.Float(), nullable=True),
    sa.Column('diag_min', sa.Float(), nullable=True),
    sa.Column('diag_contrast', sa.Float(), nullable=True),
    sa.Column('offset_margin', sa.Float(), nullable=True),
    sa.Column('lag_coherence', sa.Float(), nullable=True),
    sa.Column('png_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bullet_a_id'], ['bullet.id'], ),
    sa.ForeignKeyConstraint(['bullet_b_id'], ['bullet.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pairdiagnostic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairdiagnostic_bullet_a_id'), ['bullet_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairdiagnostic_bullet_b_id'), ['bullet_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairdiagnostic_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairdiagnostic_pipeline_version'), ['pipeline_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairdiagnostic_png_hash'), ['png_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairdiagnostic_study_id'), ['study_id'], unique=False)

    op.create_table('scantrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash_scan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lambda_s', sa.Float(), nullable=True),
    sa.Column('lambda_c', sa.Float(), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('keep', sa.Float(), nullable=False),
    sa.Column('orient', sa.Boolean(), nullable=False),
    sa.Column('striae_angle_deg', sa.Float(), nullable=True),
    sa.Column('tilt_deg', sa.Float(), nullable=True),
    sa.Column('crop_lo', sa.Integer(), nullable=True),
    sa.Column('crop_hi', sa.Integer(), nullable=True),
    sa.Column('n_signature', sa.Integer(), nullable=True),
    sa.Column('png_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npz_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'pipeline_version', name='uq_scantrace_scan_pipeline')
    )
    with op.batch_alter_table('scantrace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scantrace_content_hash_scan'), ['content_hash_scan'], unique=False)
        batch_op.create_index(batch_op.f('ix_scantrace_npz_hash'), ['npz_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_scantrace_pipeline_version'), ['pipeline_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_scantrace_png_hash'), ['png_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_scantrace_scan_id'), ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scantrace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scantrace_scan_id'))
        batch_op.drop_index(batch_op.f('ix_scantrace_png_hash'))
        batch_op.drop_index(batch_op.f('ix_scantrace_pipeline_version'))
        batch_op.drop_index(batch_op.f('ix_scantrace_npz_hash'))
        batch_op.drop_index(batch_op.f('ix_scantrace_content_hash_scan'))

    op.drop_table('scantrace')
    with op.batch_alter_table('pairdiagnostic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairdiagnostic_study_id'))
        batch_op.drop_index(batch_op.f('ix_pairdiagnostic_png_hash'))
        batch_op.drop_index(batch_op.f('ix_pairdiagnostic_pipeline_version'))
        batch_op.drop_index(batch_op.f('ix_pairdiagnostic_label'))
        batch_op.drop_index(batch_op.f('ix_pairdiagnostic_bullet_b_id'))
        batch_op.drop_index(batch_op.f('ix_pairdiagnostic_bullet_a_id'))

    op.drop_table('pairdiagnostic')
    # ### end Alembic commands ###
