#!/bin/sh
# vendor-core.sh — regenerate the bundled copy of the `verity-x3p` core crate
# inside the R package.
#
# Why this exists
# ---------------
# `R CMD build`/`R CMD check` copy the package into an isolated temporary
# directory before compiling. A Cargo `path = "../../crates/verity-x3p"`
# dependency that points *outside* the package therefore cannot be resolved in
# that copy. CRAN additionally requires every source package to be
# self-contained. So the R binding ships its own copy of the core crate under
# `src/rust/verity-x3p/`, and depends on it via an in-package relative path.
#
# To keep that copy from drifting from the canonical crate, it is *generated*
# from `crates/verity-x3p` rather than edited by hand. Run this script whenever
# the core crate's sources or dependencies change, then commit the result.
#
# The one transformation applied: the canonical crate inherits package metadata
# and the ndarray/thiserror versions from the repo-root `[workspace.package]` /
# `[workspace.dependencies]` tables (`version.workspace = true`, ...). The
# bundled copy is a standalone crate, so those inherited keys are resolved to
# the concrete values read from the root `Cargo.toml` here. `[dev-dependencies]`
# are dropped — they are only needed to build the core crate's own tests, which
# the R package never does.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
core_dir="$repo_root/crates/verity-x3p"
root_toml="$repo_root/Cargo.toml"
dest_dir="$repo_root/bindings/r/verityx3p/src/rust/verity-x3p"

[ -f "$core_dir/Cargo.toml" ] || { echo "error: cannot find core crate at $core_dir" >&2; exit 1; }
[ -f "$root_toml" ] || { echo "error: cannot find root workspace at $root_toml" >&2; exit 1; }

# Pull the workspace-inherited values from the root Cargo.toml. Each of these
# keys appears exactly once there, so a first-match grep is unambiguous.
scalar() { grep -m1 "^$1 = " "$root_toml" | sed 's/.*"\(.*\)".*/\1/'; }
version=$(scalar version)
edition=$(scalar edition)
license=$(scalar license)
repository=$(scalar repository)
authors_line=$(grep -m1 '^authors = ' "$root_toml")
ndarray_ver=$(scalar ndarray)
thiserror_ver=$(scalar thiserror)

for v in version edition license repository ndarray_ver thiserror_ver; do
  eval "val=\$$v"
  [ -n "$val" ] || { echo "error: could not read '$v' from $root_toml" >&2; exit 1; }
done
[ -n "$authors_line" ] || { echo "error: could not read 'authors' from $root_toml" >&2; exit 1; }

# Rebuild the destination from scratch so deleted source files don't linger.
rm -rf "$dest_dir"
mkdir -p "$dest_dir/src"
cp "$core_dir"/src/*.rs "$dest_dir/src/"

# Generate the standalone Cargo.toml: resolve workspace inheritance, drop
# dev-dependencies (everything from the [dev-dependencies] header onward), and
# stamp a "generated" banner so nobody hand-edits the copy.
{
  printf '# @generated by bindings/r/vendor-core.sh — do not edit by hand.\n'
  printf '# Bundled copy of crates/verity-x3p with workspace inheritance resolved.\n'
  sed -E \
    -e "s|^version\.workspace = true|version = \"$version\"|" \
    -e "s|^edition\.workspace = true|edition = \"$edition\"|" \
    -e "s|^license\.workspace = true|license = \"$license\"|" \
    -e "s|^repository\.workspace = true|repository = \"$repository\"|" \
    -e "s|^authors\.workspace = true|$authors_line|" \
    -e "s|^ndarray\.workspace = true|ndarray = \"$ndarray_ver\"|" \
    -e "s|^thiserror\.workspace = true|thiserror = \"$thiserror_ver\"|" \
    "$core_dir/Cargo.toml" | awk '/^\[dev-dependencies\]/ { exit } { print }'
} > "$dest_dir/Cargo.toml"

echo "Vendored verity-x3p -> $dest_dir"
echo "  version=$version edition=$edition ndarray=$ndarray_ver thiserror=$thiserror_ver"
echo "Remember to rebuild so src/rust/Cargo.lock updates, then commit."
