import manifest from "./gallery.json";
import type {
  GalleryComparison,
  GalleryManifest,
  GallerySpecimen,
  MarkDomain,
} from "./types";

// The curated gallery is generated by `verity-build-gallery` from the real engine on
// real catalog marks (see services/engine/verity/examples/build_gallery.py). Every
// number here is the engine's — nothing is fabricated.
const gallery = manifest as unknown as GalleryManifest;

export const GALLERY_SPECIMENS: GallerySpecimen[] = gallery.specimens;
export const GALLERY_COMPARISONS: GalleryComparison[] = gallery.comparisons;

const specimenById = new Map(GALLERY_SPECIMENS.map((s) => [s.id, s]));
const comparisonByPair = new Map<string, GalleryComparison>();
for (const c of GALLERY_COMPARISONS) {
  comparisonByPair.set(pairKey(c.aId, c.bId), c);
  comparisonByPair.set(pairKey(c.bId, c.aId), c); // selection order-independent
}

function pairKey(a: string, b: string): string {
  return `${a}__${b}`;
}

export function getSpecimen(id: string): GallerySpecimen | undefined {
  return specimenById.get(id);
}

export function getSpecimensByDomain(domain: MarkDomain): GallerySpecimen[] {
  return GALLERY_SPECIMENS.filter((s) => s.domain === domain);
}

export function findComparison(aId: string, bId: string): GalleryComparison | undefined {
  return comparisonByPair.get(pairKey(aId, bId));
}

/** A comparison of a given relation (KM/KNM), optionally constrained to a domain. */
export function pickByRelation(
  relation: "KM" | "KNM",
  domain?: MarkDomain,
): GalleryComparison | undefined {
  return GALLERY_COMPARISONS.find(
    (c) => c.relation === relation && (!domain || getSpecimen(c.aId)?.domain === domain),
  );
}

/** Any comparison in a domain (for "surprise me"); index varies the pick. */
export function pickAny(domain: MarkDomain, index: number): GalleryComparison | undefined {
  const inDomain = GALLERY_COMPARISONS.filter((c) => getSpecimen(c.aId)?.domain === domain);
  return inDomain.length ? inDomain[index % inDomain.length] : undefined;
}
