// Mirror of verity.report.ComparisonReport (the API serves this verbatim).
export interface AttributionRegion {
  x: number;
  y: number;
  h: number;
  w: number;
  corr: number;
  // normalized [0,1] coords for overlaying on a rendered preview
  x_frac: number;
  y_frac: number;
  w_frac: number;
  h_frac: number;
}

// Applicability-domain guard output (mirrors verity.decision.scope_guard).
export interface ScopeCheck {
  name: string;
  passed: boolean;
  severity: string; // "ok" | "warn" | "refuse"
  value: number;
  threshold: number;
  reason: string;
}

export interface ScopeReport {
  admissible: boolean;
  mode: string;
  domain: string;
  checks: ScopeCheck[];
  overall_reason: string;
}

export interface CompareScope {
  mark_a: ScopeReport[];
  mark_b: ScopeReport[];
}

// Single-land striated comparisons carry a diagnostic-only caution.
export interface EvidenceNote {
  single_land: boolean;
  level: string; // "diagnostic_only"
  reason: string;
}

export interface ComparisonReport {
  domain: string;
  score: number;
  score_kind: string;
  likelihood_ratio: number;
  log10_lr: number;
  // Bootstrap credible interval on log10 LR (the finite-reference uncertainty).
  log10_lr_ci_lo?: number | null;
  log10_lr_ci_hi?: number | null;
  lr_ci_method?: string | null;
  // Distinct reference sources (barrels/slides) behind a clustered credible interval.
  n_sources?: number | null;
  direction: string;
  verbal: string;
  lr_bound_log10: number | null;
  reference: {
    name: string;
    n_km: number;
    n_knm: number;
    cllr: number;
    cllr_min: number;
    auc: number;
  };
  attribution: AttributionRegion[]; // matched regions on Mark A
  attribution_b?: AttributionRegion[]; // the same matches on Mark B
  provenance: Record<string, unknown>;
  scope_note: string;
  // Applicability-domain annotation for each input (warnings ride along here).
  scope?: CompareScope;
  // Present only on the single-land striated route (marginal, diagnostic-only).
  evidence_note?: EvidenceNote;
  // API presentation: small grayscale previews of each mark to overlay regions on.
  // `a`/`b` are the form-removed striae bands; `raw_a`/`raw_b` (gallery bullets) are the
  // genuine raw land scans with the bullet's gross form still present (the ingest view).
  previews?: {
    a: number[][];
    b: number[][];
    raw_a?: number[][];
    raw_b?: number[][];
    // Full-field, native-resolution areal map for the impressed breech face (the flat heatmap
    // stage). The lean a/b previews drive the 3-D surfaces; this shows the whole face, sharply.
    areal_a?: number[][];
  };
}

// The structured out-of-scope result the API returns instead of a junk LR.
export interface RefusalResponse {
  refused: true;
  domain: string;
  reason: string;
  scope: CompareScope;
  scope_note: string;
  provenance: Record<string, unknown>;
}

export type CompareResponse = ComparisonReport | RefusalResponse;

export function isRefusal(r: CompareResponse): r is RefusalResponse {
  return (r as RefusalResponse).refused === true;
}

// ── Curated gallery (the homepage compare workspace) ─────────────────────────
// A precomputed set of real-mark comparisons, generated by `verity-build-gallery`
// from the real engine on real catalog marks — never fabricated. See lib/gallery.json.

export type MarkDomain = "striated" | "impressed" | "toolmark" | "striated-toolmark";

// One real specimen (a single mark: a bullet, a cartridge-case breech face, or a
// screwdriver edge) shown as a pickable card in the gallery.
export interface GallerySpecimen {
  id: string; // stable key, e.g. "tool-T01SB-01"
  domain: MarkDomain;
  label: string; // human label, e.g. "Screwdriver T01 · edge SB"
  source: string; // provenance dataset, e.g. "tmaRks"
  sourceUrl?: string;
  // 2-D marks (bullets, cartridge cases) carry height grids; toolmarks carry a
  // 1-D striation profile instead. The card thumbnail derives from whichever exists.
  thumb?: number[][]; // small grayscale preview grid (2-D marks)
  surface?: number[][]; // height grid for the idle SurfaceViewer render (2-D marks)
  signature?: number[]; // 1-D striation profile (toolmarks)
  pairs: string[]; // ids of specimens this has a precomputed comparison with
}

// Drives <AlignedSignatures> (the striae-alignment beat of the reveal).
export interface GallerySignatures {
  a: number[];
  b: number[];
  bandsA: { x_frac: number; w_frac: number }[];
  bandsB: { x_frac: number; w_frac: number }[];
}

// Drives <CalibrationChart> (the score-on-the-population beat).
export interface GalleryCalibration {
  km: number[];
  knm: number[];
  score: number;
  lrLabel: string;
}

// One real CMR window/cell vote: the alignment it proposes (plot coords `x`,`y` in the
// engine's own units), whether it joined the consensus cluster, and labelled values for hover.
export interface GalleryVote {
  x: number; // plot coords in [0,1] (consensus-centered, tolerance-scaled)
  y: number;
  consensus: boolean;
  tip?: Record<string, string>; // ordered label → value pairs, shown on mouseover (real votes only)
}

// The real per-window CMR votes for the consensus stage — `areal` (impressed: a Δx/Δy
// translation plane, twist on hover) or `1d` (striated/toolmark: lag vs correlation).
export interface GalleryCmr {
  kind: "areal" | "1d";
  axisX: string;
  axisY: string;
  nConsensus: number;
  votes: GalleryVote[];
}

// One precomputed comparison between two specimens — everything the reveal animates.
export interface GalleryComparison {
  id: string; // "<aId>__<bId>"
  aId: string;
  bId: string;
  relation: "KM" | "KNM"; // ground-truth same/different source (NOT the LR sign)
  report: ComparisonReport; // the full report <ReportView> renders
  signatures?: GallerySignatures; // present for striated / toolmark marks
  calibration: GalleryCalibration;
  cmr?: GalleryCmr; // real per-window votes for the consensus scatter (curated gallery only)
}

export interface GalleryManifest {
  version: string; // scorer-config hash — ties the precomputed numbers to a scorer
  generatedAt?: string;
  specimens: GallerySpecimen[];
  comparisons: GalleryComparison[];
}

// Unifies a gallery pick and a live upload through one report pipeline.
export type Provenance = "gallery" | "upload";

export interface BenchResult {
  report: CompareResponse;
  provenance: Provenance;
  relation?: "KM" | "KNM"; // gallery only
  source?: string; // gallery provenance label
  signatures?: GallerySignatures; // present when the reveal can animate alignment
  calibration?: GalleryCalibration; // present when the reveal can animate calibration
}
