# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib verityx3p, .registration = TRUE
NULL

#' Read an X3P file into raw components.
#'
#' `data`/`mask` are returned X-fastest, i.e. ordered to fill an `nx`-by-`ny`
#' R matrix in column-major order (the `x3ptools` convention).
rust_read_x3p <- function(path, verify_checksums) .Call(wrap__rust_read_x3p, path, verify_checksums)

#' Write raw components to an X3P file. `data` is X-fastest (column-major from
#' an `nx`-by-`ny` matrix); `z_type` is `"D"` (float64) or `"F"` (float32).
rust_write_x3p <- function(path, data, mask, nx, ny, increment_x, increment_y, z_type) .Call(wrap__rust_write_x3p, path, data, mask, nx, ny, increment_x, increment_y, z_type)

# nolint end
